_schema: _schema
paths:
  uploads: uploads
  static: ''
collections_config:
  content_posts:
    path: content/posts
    name: Content Posts
    icon: content_paste
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  content_works:
    path: content/works
    name: Content Works
    icon: content_copy
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  i18n_locales:
    path: i18n/locales
    name: I18n Locales
    icon: fan_focus
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  public:
    path: public
    name: Public
    icon: public
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Europe/Kiev
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: false
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
