collections:
  posts:
    output: true
    path: content/posts
    fields:
      title:
        type: text
        label: Заголовок
      titleUa:
        type: text
        label: Заголовок (ua)
      date:
        type: datetime
        label: Дата
      dateUa:
        type: datetime
        label: Дата (ua)
      topic:
        type: text
        label: Тематика
      topicUa:
        type: text
        label: Тематика (ua)
      description:
        type: textarea
        label: Описание
      descriptionUa:
        type: textarea
        label: Описание (ua)

  works:
    output: true
    path: content/works
    fields:
      title:
        type: text
        label: Заголовок
      titleUa:
        type: text
        label: Заголовок (ua)
      img:
        type: image
        label: Изображение
        folder: /public/images/works
        default: /images/works/default.png
      date:
        type: datetime
        label: Дата
      topic:
        type: text
        label: Тематика
      topicUa:
        type: text
        label: Тематика (ua)
      description:
        type: textarea
        label: Описание
      descriptionUa:
        type: textarea
        label: Описание (ua)
