backend:
  name: git-gateway
  branch: main # Ветка репозитория
media_folder: "public/images/works" # Папка для загрузки медиа
public_folder: "/images/works" # Путь для доступа к медиа
collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title (UA)", name: "titleUa", widget: "string" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Date (UA)", name: "dateUa", widget: "string" }
      - { label: "Topic", name: "topic", widget: "string" }
      - { label: "Topic (UA)", name: "topicUa", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Description (UA)", name: "descriptionUa", widget: "text" }
  - name: "works"
    label: "Works"
    folder: "content/works"
    create: true
    fields:
      - { label: "ID", name: "id", widget: "number" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Title (UA)", name: "titleUa", widget: "string" }
      - { label: "Image", name: "img", widget: "image" }
      - { label: "Date", name: "date", widget: "string" }
      - { label: "Topic", name: "topic", widget: "string" }
      - { label: "Topic (UA)", name: "topicUa", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Description (UA)", name: "descriptionUa", widget: "text" }